
requests:
  - id: defilama
    url: https://api.example.com/endpoint1
    timeout: 5s
  - id: request2
    url: https://api.example.com/endpoint2
    timeout: 10s
  - id: request3
    url: https://api.example.com/endpoint3
    timeout: 8s
