version: '3.9'
services:
  redis:
    image: redis:latest
    container_name: redis-api
    ports:
      - ${REDIS_PORT}:6379
    restart: always
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    networks:
      - api-network

  go-api:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - api-network
    ports:
      - 8080-8085:8080
    deploy:
      replicas: ${GO_API_REPLICAS}
    restart: always
    depends_on:
      - redis

  nginx:
    image: nginx
    container_name: nginx-api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - api-network
    ports:
      - 80:80
      - 443:443
    depends_on:
      - go-api
    environment:
      - NGINX_WORKER_PROCESSES=${WORKERS}
    deploy:
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: any


volumes:
  redis_data:
networks:
  api-network:
